### ISSUE TITLE
Finalize content assist features indicated in the following task list

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/WP3#29]
- [x] EAttribute
- [x] EReference
- [x] EOperation 
- [x] EParameter
- [x] ESuperType, EGenericSuperType
- [x] EException, EGenericException
- [x] EOpposites

**Comment by emrekirmizi** [comment]
In the meantime I published my C3 (Code Completion Core) engine [https://www.npmjs.com/package/antlr4-c3], which could give you more ideas. – Mike Lischke
