### ISSUE TITLE
Improve Document Lifecycle in terms of Save Operation

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/WP3#58]
Save operations must preserve the layout of the programs unless it is updated outside the user's editor.

**Comment by y3seker** [comment]
Part of the issue still remains. If ecore file updates when AIE Editor closed, editor won't reflect those updates on opening due to existing source annotation. Hash (or similar) validation still needed.

**Comment by ferhaterata** [comment]
Yeah, we forgot to consider that case.
